Change comments to giscus
OI-wiki/mkdocs-material pull request #37
Opened 2022-08-02 23:18 UTC by littlefrogfromthenorth

1. 合并的时候记着新建个分支 `giscus`
2. 开个  `repo` 用来评论的
3. 把 `repo-id` 啥的都替换成这个 `repo`

2022-08-03 01:45 UTC, ouuan requested changes

2022-08-03 01:45 UTC, ouuan commented on src/partials/integrations/disqus.html
> +<form id="comments-form" onsubmit="return false;" data-no-instant>
这里不用套 form 吧

2022-08-03 01:45 UTC, ouuan commented on src/partials/integrations/disqus.html
>  <h2 id="__comments" data-no-instant>{{ lang.t("meta.comments") }}</h2>
这个标题也可以删掉，本来就自带“x 条评论”的提示，而且 giscus 有对文章的 reactions，没这个标题会更融洽一些

2022-08-03 01:45 UTC, ouuan commented on src/partials/integrations/disqus.html
> +        data-category="Announcements"
这个创建 Discussions 的时候可以改名叫 Comments

2022-08-03 01:45 UTC, ouuan commented on src/partials/integrations/disqus.html
> +        data-mapping="url"
```suggestion
        data-mapping="specific"
        data-term="{{ page.title | default("404", true) }}"
```

好像上面设了一个 `pageID` 变量，只不过原来 Gitalk 就没用 🤔

2022-08-03 01:45 UTC, ouuan commented on src/partials/integrations/disqus.html
> +        data-lang="zh-CN"
这个在 i18n 是不是要改一下，怎么改我不太清楚

2022-08-03 01:45 UTC, ouuan commented on src/partials/integrations/disqus.html
> +        crossorigin="anonymous"
```suggestion
		data-loading="lazy"
        crossorigin="anonymous"
```

lazy loading 不加白不加（

2022-08-03 01:45 UTC, ouuan commented on src/partials/integrations/disqus.html
> +<div class="giscus" id="comments-container" data-no-instant>
这个 id 有什么用吗？感觉用不到的时候不如不设 id

2022-08-03 03:16 UTC, littlefrogfromthenorth commented on src/partials/integrations/disqus.html
> +        data-mapping="url"
pageID 没用, 只能从他给那几个里面选

2022-08-03 03:19 UTC, ouuan commented on src/partials/integrations/disqus.html
> +        data-mapping="url"
> pageID 没用

我是说可以用这个 HTML 模板的 `pageID` 变量代替 `{{ page.title | default("404", true) }}`，不知道你指的是什么..

> 只能从他给那几个里面选

这个就是选的 `specific` 然后再指定 `data-term` 啊

2022-08-03 04:11 UTC, littlefrogfromthenorth commented on src/partials/integrations/disqus.html
> +        data-mapping="url"
![image](https://user-images.githubusercontent.com/49180735/182522430-c9141531-1226-4ec7-a251-25234ab6a21b.png)

2022-08-03 04:12 UTC, littlefrogfromthenorth commented on src/partials/integrations/disqus.html
> +        data-mapping="url"
咱好像就不应该选specific

2022-08-03 04:17 UTC, littlefrogfromthenorth commented on src/partials/integrations/disqus.html
> +        data-category="Announcements"
这你就转换之后改一下,不是光改repo名,还有个repo-id要在giscus.app上获取的,我这里没有Member也没法获取,这填的就本地测试用的,就现部署现改即可

2022-08-03 04:40 UTC, ouuan commented on src/partials/integrations/disqus.html
> +        data-mapping="url"
特定 discussion 号是 number 不是 specific

2022-08-03 05:27 UTC, littlefrogfromthenorth commented on src/partials/integrations/disqus.html
> +        data-mapping="url"
哦哦哦, 我看错了

2022-09-05 05:46 UTC, littlefrogfromthenorth commented
捞

2022-12-04 13:06 UTC, ouuan commented on src/partials/integrations/disqus.html
> +          data-category-id="DIC_kwDOHwYTIc4CQkz1"
```suggestion
          data-repo="OI-wiki/gitment"
          data-repo-id="MDEwOlJlcG9zaXRvcnkxNDQzODg5NjU"
          data-category="Comments"
          data-category-id="DIC_kwDOCJszZc4CS53G"
```

2022-12-04 14:55 UTC, ouuan approved these changes

2022-12-04 14:57 UTC, merged